name: Scala Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Docker
      	run: docker-compose up -d
      	working-directory: docker
    - name: Integration Tests
      	run: sbt it:test
      	working-directory: redis-scala-client
